version: '3.8'

services:
  utawakufinder-db:
    image: postgres:17
    environment:
      - POSTGRES_DB=utawakufinder
      - POSTGRES_USER=utawaku
      - POSTGRES_PASSWORD=utawakupass123
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    network_mode: "host"
    volumes:
      - ./data:/app/data
      - .:/app
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=postgresql://utawaku:utawakupass123@localhost:5433/utawakufinder
    depends_on:
      - utawakufinder-db
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    network_mode: "host"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:9030
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  data:
  postgres_data: