version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    network_mode: "host"
    volumes:
      - ./data:/app/data
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    network_mode: "host"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:9030
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  data: